const styles = StyleSheet.create({
  container: {
    flex: 1,
    // Gradiente para web: pode usar expo-linear-gradient ou css para web
    backgroundColor: '#16192e',
    minHeight: '100vh',
  },
  header: {
    backgroundColor: '#1a1a2e',
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: '#00f0ff',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 10,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
    letterSpacing: 2,
    marginBottom: 15,
    alignSelf: 'center',
    textShadowColor: '#00f0ff',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  navWrapper: {
    position: 'relative',
    marginVertical: 10,
  },
  nav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 12,
  },
  navButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    transitionProperty: 'background',
    transitionDuration: '0.2s',
  },
  navButtonText: {
    color: '#888',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 1,
    userSelect: 'none',
  },
  navButtonTextActive: {
    color: '#00f0ff',
    fontWeight: 'bold',
    textShadowColor: '#00f0ff',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 14,
  },
  underline: {
    position: 'absolute',
    height: 6,
    bottom: 0,
    borderRadius: 3,
    overflow: 'hidden',
    backgroundColor: 'transparent',
    shadowColor: '#00f0ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 8,
  },
  underlineBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#00f0ff',
    opacity: 0.4,
  },
  runningLight: {
    position: 'absolute',
    top: 0,
    width: '30%',
    height: '100%',
    backgroundColor: '#ffffff',
    opacity: 0.8,
    borderRadius: 3,
    shadowColor: '#00f0ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 18,
    elevation: 14,
  },
  content: {
    padding: 30,
    flexGrow: 1,
    gap: 22,
  },
  section: {
    marginBottom: 30,
    backgroundColor: '#22253c',
    borderRadius: 18,
    padding: 22,
    shadowColor: '#00f0ff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    fontSize: 23,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#fff',
    letterSpacing: 1,
    textShadowColor: '#00f0ff',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 14,
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderWidth: 1,
    borderColor: '#00f0ff',
    borderRadius: 7,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 18,
    fontSize: 16,
    color: '#16192e',
  },
  button: {
    backgroundColor: '#00f0ff',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#00f0ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 8,
  },
  buttonText: {
    color: '#16192e',
    fontWeight: 'bold',
    fontSize: 18,
    letterSpacing: 1,
  },
  footer: {
    backgroundColor: '#22253c',
    padding: 18,
    alignItems: 'center',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginTop: 30,
    shadowColor: '#00f0ff',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 2,
  },
});